### ISSUE TITLE
Add Alert and Notifications

### ISSUE THREAD

**Issue by CarroCremello** [CarroForslund/fsjs-project2#2]
## Todo

- [ ] When the page loads the purple alert should be visible, but the user should be able to close the alert by clicking the X button.

- [ ] Include a green notification dot next to the bell icon in the navigation header.

- [ ] Display at least two notifications when the user clicks the alerts icon. This could be a pop-up window or dropdown menu.
