### ISSUE TITLE
Message User Widget

### ISSUE THREAD

**Issue by CarroCremello** [CarroForslund/fsjs-project2#3]
## Todo

- [x] Add functionality to "send" button
- [x] Display error message if user isn't selected and/or message is empty when the "send" button is clicked
- [x] Display confirmation message when valid user and message is typed in and "send" button is clicked
